<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Research Team">
<meta name="dcterms.date" content="2026-03-29">

<title>Intergenerational Educational Mobility in Uzbekistan</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="00_main_files/libs/clipboard/clipboard.min.js"></script>
<script src="00_main_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="00_main_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="00_main_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="00_main_files/libs/quarto-html/popper.min.js"></script>
<script src="00_main_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="00_main_files/libs/quarto-html/anchor.min.js"></script>
<link href="00_main_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="00_main_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="00_main_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="00_main_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="00_main_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#related-literature" id="toc-related-literature" class="nav-link" data-scroll-target="#related-literature"><span class="header-section-number">2</span> Related Literature</a>
  <ul class="collapse">
  <li><a href="#concepts-and-measurement" id="toc-concepts-and-measurement" class="nav-link" data-scroll-target="#concepts-and-measurement"><span class="header-section-number">2.1</span> Concepts and Measurement</a></li>
  <li><a href="#global-evidence-and-developing-country-patterns" id="toc-global-evidence-and-developing-country-patterns" class="nav-link" data-scroll-target="#global-evidence-and-developing-country-patterns"><span class="header-section-number">2.2</span> Global Evidence and Developing-Country Patterns</a></li>
  <li><a href="#transition-economies-comparator-settings-and-the-uzbek-case" id="toc-transition-economies-comparator-settings-and-the-uzbek-case" class="nav-link" data-scroll-target="#transition-economies-comparator-settings-and-the-uzbek-case"><span class="header-section-number">2.3</span> Transition Economies, Comparator Settings, and the Uzbek Case</a></li>
  <li><a href="#identification-limits-and-contribution" id="toc-identification-limits-and-contribution" class="nav-link" data-scroll-target="#identification-limits-and-contribution"><span class="header-section-number">2.4</span> Identification Limits and Contribution</a></li>
  </ul></li>
  <li><a href="#data-and-measurement" id="toc-data-and-measurement" class="nav-link" data-scroll-target="#data-and-measurement"><span class="header-section-number">3</span> Data and Measurement</a>
  <ul class="collapse">
  <li><a href="#core-data" id="toc-core-data" class="nav-link" data-scroll-target="#core-data"><span class="header-section-number">3.1</span> Core Data</a></li>
  <li><a href="#education-measures" id="toc-education-measures" class="nav-link" data-scroll-target="#education-measures"><span class="header-section-number">3.2</span> Education Measures</a></li>
  <li><a href="#mobility-outcomes" id="toc-mobility-outcomes" class="nav-link" data-scroll-target="#mobility-outcomes"><span class="header-section-number">3.3</span> Mobility Outcomes</a></li>
  <li><a href="#covariates" id="toc-covariates" class="nav-link" data-scroll-target="#covariates"><span class="header-section-number">3.4</span> Covariates</a></li>
  <li><a href="#pandemic-mechanism-variables" id="toc-pandemic-mechanism-variables" class="nav-link" data-scroll-target="#pandemic-mechanism-variables"><span class="header-section-number">3.5</span> Pandemic Mechanism Variables</a></li>
  </ul></li>
  <li><a href="#empirical-strategy" id="toc-empirical-strategy" class="nav-link" data-scroll-target="#empirical-strategy"><span class="header-section-number">4</span> Empirical Strategy</a>
  <ul class="collapse">
  <li><a href="#module-a-mobility-levels-and-trends" id="toc-module-a-mobility-levels-and-trends" class="nav-link" data-scroll-target="#module-a-mobility-levels-and-trends"><span class="header-section-number">4.1</span> Module A: Mobility Levels and Trends</a></li>
  <li><a href="#module-b-correlates-of-mobility" id="toc-module-b-correlates-of-mobility" class="nav-link" data-scroll-target="#module-b-correlates-of-mobility"><span class="header-section-number">4.2</span> Module B: Correlates of Mobility</a></li>
  <li><a href="#module-c-pandemic-era-mechanisms" id="toc-module-c-pandemic-era-mechanisms" class="nav-link" data-scroll-target="#module-c-pandemic-era-mechanisms"><span class="header-section-number">4.3</span> Module C: Pandemic-Era Mechanisms</a></li>
  </ul></li>
  <li><a href="#descriptive-results" id="toc-descriptive-results" class="nav-link" data-scroll-target="#descriptive-results"><span class="header-section-number">5</span> Descriptive Results</a>
  <ul class="collapse">
  <li><a href="#sample-composition-and-completeness" id="toc-sample-composition-and-completeness" class="nav-link" data-scroll-target="#sample-composition-and-completeness"><span class="header-section-number">5.1</span> Sample Composition and Completeness</a></li>
  <li><a href="#national-mobility-metrics-by-wave" id="toc-national-mobility-metrics-by-wave" class="nav-link" data-scroll-target="#national-mobility-metrics-by-wave"><span class="header-section-number">5.2</span> National Mobility Metrics by Wave</a></li>
  <li><a href="#transition-structure" id="toc-transition-structure" class="nav-link" data-scroll-target="#transition-structure"><span class="header-section-number">5.3</span> Transition Structure</a></li>
  <li><a href="#descriptive-heterogeneity" id="toc-descriptive-heterogeneity" class="nav-link" data-scroll-target="#descriptive-heterogeneity"><span class="header-section-number">5.4</span> Descriptive Heterogeneity</a></li>
  </ul></li>
  <li><a href="#correlates-of-educational-mobility" id="toc-correlates-of-educational-mobility" class="nav-link" data-scroll-target="#correlates-of-educational-mobility"><span class="header-section-number">6</span> Correlates of Educational Mobility</a>
  <ul class="collapse">
  <li><a href="#pooled-persistence-trend-model" id="toc-pooled-persistence-trend-model" class="nav-link" data-scroll-target="#pooled-persistence-trend-model"><span class="header-section-number">6.1</span> Pooled Persistence-Trend Model</a></li>
  <li><a href="#attainment-score-model" id="toc-attainment-score-model" class="nav-link" data-scroll-target="#attainment-score-model"><span class="header-section-number">6.2</span> Attainment-Score Model</a></li>
  <li><a href="#upward-mobility-models" id="toc-upward-mobility-models" class="nav-link" data-scroll-target="#upward-mobility-models"><span class="header-section-number">6.3</span> Upward Mobility Models</a></li>
  <li><a href="#heterogeneity-in-persistence" id="toc-heterogeneity-in-persistence" class="nav-link" data-scroll-target="#heterogeneity-in-persistence"><span class="header-section-number">6.4</span> Heterogeneity in Persistence</a></li>
  <li><a href="#household-support-environment-from-hbs" id="toc-household-support-environment-from-hbs" class="nav-link" data-scroll-target="#household-support-environment-from-hbs"><span class="header-section-number">6.5</span> Household Support Environment from HBS</a></li>
  </ul></li>
  <li><a href="#bounded-lits-iv-child-module-extension" id="toc-bounded-lits-iv-child-module-extension" class="nav-link" data-scroll-target="#bounded-lits-iv-child-module-extension"><span class="header-section-number">7</span> Bounded LiTS IV Child Module Extension</a>
  <ul class="collapse">
  <li><a href="#sample-and-disruption-profile" id="toc-sample-and-disruption-profile" class="nav-link" data-scroll-target="#sample-and-disruption-profile"><span class="header-section-number">7.1</span> Sample and Disruption Profile</a></li>
  <li><a href="#main-regression-takeaway" id="toc-main-regression-takeaway" class="nav-link" data-scroll-target="#main-regression-takeaway"><span class="header-section-number">7.2</span> Main Regression Takeaway</a></li>
  </ul></li>
  <li><a href="#discussion-and-policy-implications" id="toc-discussion-and-policy-implications" class="nav-link" data-scroll-target="#discussion-and-policy-implications"><span class="header-section-number">8</span> Discussion and Policy Implications</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">9</span> Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">10</span> Conclusion</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="00_main.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Intergenerational Educational Mobility in Uzbekistan</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Research Team </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="abstract">Abstract</h2>
<p>This paper studies intergenerational educational mobility in Uzbekistan using the 2010, 2016, and 2022-23 waves of the Life in Transition Survey (LiTS). It asks how strongly educational attainment is associated across generations, which household and regional characteristics are correlated with mobility, and what the 2022-23 child module suggests about household learning conditions during pandemic disruption.</p>
<p>The paper’s contribution is a reproducible multi-wave mobility profile built around descriptive and associational evidence. The national rank-rank slope rises from 0.133 in 2010 to 0.307 in 2016 and remains elevated at 0.253 in 2022-23. In pooled correlates models, parental rank is positively associated with respondent rank, the 2016 persistence interaction is stronger than in 2010, and parental education remains the clearest predictor of attainment. The LiTS IV child module documents widespread disruption and household-based support, but adjusted parental-education gaps in education stoppage are near zero in the baseline specification and fragile across alternative split rules.</p>
<p>The results point to substantial educational persistence and to the importance of household support conditions, but the time profile is clearer between 2010 and 2016 than between 2016 and 2022-23, and the child-module evidence does not identify a causal pandemic mechanism.</p>
</section>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>Educational mobility links family background to the allocation of opportunity. When mobility is low, parental education remains a strong predictor of children’s schooling, and the distribution of skills is shaped more by inherited circumstance than by individual potential.</p>
<p>Uzbekistan is an important setting for this question. The country combines a young population, persistent regional inequality, and a policy agenda centered on human capital and productivity growth. At the same time, market transition, urbanization, higher-education expansion, and digital change have altered both the returns to schooling and the ways households support children’s learning.</p>
<p>This paper uses LiTS repeated cross-sections from 2010, 2016, and 2022-23 to provide a structured profile of intergenerational educational mobility in Uzbekistan. It makes three contributions. First, it documents national mobility patterns using a locked bundle of measures: a rank-rank slope, upward mobility, downward mobility, and same-category persistence. Second, it estimates pooled correlates models with a disciplined set of household and regional controls. Third, it adds a short LiTS IV child-module extension on pandemic-era disruption and support patterns.</p>
<p>The claims are intentionally limited by design. Module A is descriptive, Module B is associational, and Module C is a bounded non-causal extension. Descriptive persistence rises sharply from 2010 to 2016 and remains above the 2010 level in 2022-23, while the pooled persistence model indicates a clearer 2016 strengthening than an additional 2022 shift. The paper therefore emphasizes levels, correlates, and household constraints rather than a causal mechanism claim. Section 2 positions the paper in the literature, Section 3 describes the data and measurement choices, Sections 4-7 present the empirical design and results, and Sections 8-10 discuss interpretation, limitations, and conclusion.</p>
</section>
<section id="related-literature" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="related-literature"><span class="header-section-number">2</span> Related Literature</h2>
<section id="concepts-and-measurement" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="concepts-and-measurement"><span class="header-section-number">2.1</span> Concepts and Measurement</h3>
<p>Intergenerational educational mobility links family background to both equality of opportunity and the allocation of skills. When parental schooling strongly predicts children’s attainment, educational outcomes reflect inherited circumstances as well as effort and talent. For that reason, mobility matters not only as a fairness concern, but also as a compact way to ask whether schooling systems convert demographic growth and human potential into broadly shared opportunity or instead reproduce educational advantage across generations <span class="citation" data-cites="torche_2015 causa_johansson_2010 neidhoefer_etal_2024">(<a href="#ref-torche_2015" role="doc-biblioref">Torche 2015</a>; <a href="#ref-causa_johansson_2010" role="doc-biblioref">Causa and Johansson 2010</a>; <a href="#ref-neidhoefer_etal_2024" role="doc-biblioref">Neidhöfer et al. 2024</a>)</span>.</p>
<p>The literature also cautions against treating any single statistic as a complete description of opportunity. Mobility measures summarize intergenerational association rather than recovering a full structural account of equality of opportunity, and recent evidence shows that cross-country rankings can move materially with coding choices, estimator selection, and sample definitions <span class="citation" data-cites="torche_2015 stromberg_engzell_2025">(<a href="#ref-torche_2015" role="doc-biblioref">Torche 2015</a>; <a href="#ref-stromberg_engzell_2025" role="doc-biblioref">Strömberg and Engzell 2025</a>)</span>. For a study built on repeated cross-sections with modest questionnaire differences across waves, that is a direct argument against relying on one headline number.</p>
<p>This paper therefore uses a locked bundle of category-based and rank-based measures. Category transitions retain an intuitive interpretation by asking whether respondents surpass, match, or fall below parental schooling categories. Rank-based measures are better suited to cross-wave comparison because they locate respondents within each wave’s educational distribution and are less sensitive to aggregate educational expansion and minor coding differences. The two families answer related but not identical questions: category rates preserve substantive interpretability, whereas rank-based persistence provides the preferred benchmark for comparing waves <span class="citation" data-cites="torche_2015 weide_etal_2024 stromberg_engzell_2025">(<a href="#ref-torche_2015" role="doc-biblioref">Torche 2015</a>; <a href="#ref-weide_etal_2024" role="doc-biblioref">Weide et al. 2024</a>; <a href="#ref-stromberg_engzell_2025" role="doc-biblioref">Strömberg and Engzell 2025</a>)</span>.</p>
</section>
<section id="global-evidence-and-developing-country-patterns" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="global-evidence-and-developing-country-patterns"><span class="header-section-number">2.2</span> Global Evidence and Developing-Country Patterns</h3>
<p>Comparative evidence establishes three regularities. First, educational mobility varies widely across countries and cohorts rather than converging mechanically with development. Second, many developing settings still display lower average mobility than richer economies even after substantial educational expansion. Third, rising schooling access does not automatically weaken intergenerational persistence; broader participation can coexist with durable family-background gradients in who reaches upper-secondary and tertiary levels <span class="citation" data-cites="hertz_2008 weide_etal_2024 duong_2024">(<a href="#ref-hertz_2008" role="doc-biblioref">Hertz et al. 2008</a>; <a href="#ref-weide_etal_2024" role="doc-biblioref">Weide et al. 2024</a>; <a href="#ref-duong_2024" role="doc-biblioref">Duong 2024</a>)</span>.</p>
<p>That point matters for interpretation. Expansion in average schooling is not itself evidence that opportunity has become less dependent on parental background. Earlier comparative work and more recent evidence from developing regions both show that cohort progress and persistent gradients can coexist for long periods <span class="citation" data-cites="chevalier_denny_mcmahon_2009 razzu_wambile_2022">(<a href="#ref-chevalier_denny_mcmahon_2009" role="doc-biblioref">Chevalier, Denny, and McMahon 2009</a>; <a href="#ref-razzu_wambile_2022" role="doc-biblioref">Razzu and Wambile 2022</a>)</span>. For the present paper, the lesson is that Uzbekistan should not be read through a simple modernization narrative in which broader access mechanically implies weaker educational inheritance.</p>
</section>
<section id="transition-economies-comparator-settings-and-the-uzbek-case" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="transition-economies-comparator-settings-and-the-uzbek-case"><span class="header-section-number">2.3</span> Transition Economies, Comparator Settings, and the Uzbek Case</h3>
<p>Transition settings are especially relevant because market liberalization, institutional restructuring, and uneven regional adjustment can alter both schooling opportunity and the household strategies through which education is reproduced. The post-socialist literature does not point to a single mobility path. Comparative evidence shows substantial heterogeneity across former socialist settings, and country studies suggest that common Soviet legacies do not determine later mobility outcomes on their own <span class="citation" data-cites="verashchagina_2012 bruck_esenaliev_2018">(<a href="#ref-verashchagina_2012" role="doc-biblioref">Verashchagina 2012</a>; <a href="#ref-bruck_esenaliev_2018" role="doc-biblioref">Brück and Esenaliev 2018</a>)</span>.</p>
<p>Kyrgyzstan is the closest Central Asian comparator in the published literature cited here, while Turkey provides a second disciplined comparison because it combines middle-income status with strong spatial disparities in school availability, household inputs, and educational inequality. Evidence from Turkey shows that mobility is higher in places with better schooling opportunity and stronger home resources, which helps motivate this paper’s attention to region, cohort, and place-based heterogeneity <span class="citation" data-cites="aydemir_yazici_2019">(<a href="#ref-aydemir_yazici_2019" role="doc-biblioref">Aydemir and Yazici 2019</a>)</span>. Some comparator studies go further by exploiting reform-driven or provincial variation in schooling opportunity <span class="citation" data-cites="akarcay_polat_2017 urbina_2018">(<a href="#ref-akarcay_polat_2017" role="doc-biblioref">Akarçay-Gürbüz and Polat 2017</a>; <a href="#ref-urbina_2018" role="doc-biblioref">Urbina 2018</a>)</span>. Those papers are useful here not because the present study adopts their design, but because they clarify what a genuinely causal architecture would require and why the claims in this manuscript remain more limited. Broader evidence linking mobility to local development conditions likewise supports the inclusion of region and cohort effects while reinforcing an associational reading of the pooled coefficients <span class="citation" data-cites="guell_etal_2018 neidhoefer_etal_2024">(<a href="#ref-guell_etal_2018" role="doc-biblioref">Guell et al. 2018</a>; <a href="#ref-neidhoefer_etal_2024" role="doc-biblioref">Neidhöfer et al. 2024</a>)</span>.</p>
<p>Uzbekistan deserves separate attention rather than inference from neighboring settings or richer-country evidence alone. World Bank and UNICEF diagnostics point to persistent disparities across region, urban and rural location, gender, tertiary pathways, and the quality of household learning environments <span class="citation" data-cites="wb_uzb_2018 unicef_sitan_2020 unicef_sitan_2024 wb_gender_2024">(<a href="#ref-wb_uzb_2018" role="doc-biblioref">World Bank 2018</a>, <a href="#ref-wb_gender_2024" role="doc-biblioref">2024</a>; <a href="#ref-unicef_sitan_2020" role="doc-biblioref">UNICEF Uzbekistan 2020</a>, <a href="#ref-unicef_sitan_2024" role="doc-biblioref">2024</a>)</span>. These sources are not mobility designs, but they establish why parental education, place-based conditions, and household support capacity are plausible correlates of educational mobility in Uzbekistan and why a descriptive benchmark is policy-relevant even without a causal design. The tertiary margin is especially important. World Bank analysis of Uzbekistan’s higher-education system highlights long-standing constraints in access, quality, governance, and labor-market relevance <span class="citation" data-cites="wb_modernizing_tertiary_2017">(<a href="#ref-wb_modernizing_tertiary_2017" role="doc-biblioref">World Bank 2014</a>)</span>. In a setting where bottlenecks remain strongest at advanced levels of schooling, intergenerational persistence may survive even when basic and secondary participation improve.</p>
<p>Recent mobility patterns also need to be read against a changed policy backdrop. Since 2017, Uzbekistan’s education system has moved through a broad reform cycle spanning preschool expansion, sector restructuring, renewed attention to quality and management, and major efforts to widen tertiary access. Official diagnostics and partnership documents frame this period as one of institutional reorganization and sustained reform priority rather than policy stasis <span class="citation" data-cites="wb_uzb_2018 unicef_compact_2024 unicef_sitan_2024">(<a href="#ref-wb_uzb_2018" role="doc-biblioref">World Bank 2018</a>; <a href="#ref-unicef_compact_2024" role="doc-biblioref">UNICEF 2024</a>; <a href="#ref-unicef_sitan_2024" role="doc-biblioref">UNICEF Uzbekistan 2024</a>)</span>. For this paper, that context matters not as a source of clean treatment variation, but because the 2022-23 wave reflects an environment of expanded access and system change. At the same time, the reform literature continues to distinguish gains in access from the harder problems of quality, equity, and labor-market alignment <span class="citation" data-cites="wb_modernizing_tertiary_2017 wb_uzb_2018">(<a href="#ref-wb_modernizing_tertiary_2017" role="doc-biblioref">World Bank 2014</a>, <a href="#ref-wb_uzb_2018" role="doc-biblioref">2018</a>)</span>. The manuscript therefore does not attribute observed mobility patterns to reforms; it treats reform as context that sharpens interpretation of cohort, place, and household differences.</p>
</section>
<section id="identification-limits-and-contribution" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="identification-limits-and-contribution"><span class="header-section-number">2.4</span> Identification Limits and Contribution</h3>
<p>The literature relevant to this project falls into three broad groups. One documents intergenerational mobility descriptively, using transition matrices, rank correlations, or related persistence measures to summarize how strongly children’s schooling tracks parental background. A second identifies causal effects of schooling access or reform by exploiting exogenous variation across place, cohort, or policy exposure. A third, especially after 2020, studies pandemic-era learning disruption and the unequal burden that school closures shifted back onto households <span class="citation" data-cites="urbina_2018 alam_tiwari_2020 munoz_najar_etal_2021">(<a href="#ref-urbina_2018" role="doc-biblioref">Urbina 2018</a>; <a href="#ref-alam_tiwari_2020" role="doc-biblioref">Alam and Tiwari 2020</a>; <a href="#ref-munoz_najar_etal_2021" role="doc-biblioref">Muñoz-Najar et al. 2021</a>)</span>. These literatures are complementary, but they support different kinds of claims.</p>
<p>This paper belongs mainly in the first category. Its core evidence comes from repeated LiTS cross-sections rather than a panel following fixed families over time, so it can describe population-level persistence and estimate pooled correlates, but it cannot isolate within-family causal change or identify the effects of reforms. The same discipline applies to Module C. Global and Uzbekistan-specific pandemic evidence justifies asking whether lower-parent-education households report greater disruption, but the LiTS IV child module remains a small cross-sectional subsample and does not support a causal account of household mechanisms <span class="citation" data-cites="alam_tiwari_2020 munoz_najar_etal_2021 iqbal_patrinos_2025">(<a href="#ref-alam_tiwari_2020" role="doc-biblioref">Alam and Tiwari 2020</a>; <a href="#ref-munoz_najar_etal_2021" role="doc-biblioref">Muñoz-Najar et al. 2021</a>; <a href="#ref-iqbal_patrinos_2025" role="doc-biblioref">Iqbal and Patrinos 2025</a>)</span>.</p>
<p>Taken together, the literature leaves a clear but modest empirical gap. Comparative work on intergenerational educational mobility is now extensive, developing-country evidence is growing, and post-socialist comparators are increasingly informative. For Uzbekistan, however, the evidence base remains weighted toward sector diagnostics and policy discussion rather than a reproducible multi-wave profile of how educational attainment is transmitted across generations. The contribution of this paper is therefore narrow by design but substantively useful: it provides a transparent benchmark for educational mobility in Uzbekistan using a locked bundle of persistence measures, a pooled associational framework, and a short descriptive child-module extension. Its aim is not to evaluate reforms or pandemic shocks, but to place Uzbekistan into the comparative mobility conversation with an empirical profile that is explicit about measurement choices, identification limits, and policy-relevant heterogeneity <span class="citation" data-cites="weide_etal_2024 bruck_esenaliev_2018 wb_uzb_2018">(<a href="#ref-weide_etal_2024" role="doc-biblioref">Weide et al. 2024</a>; <a href="#ref-bruck_esenaliev_2018" role="doc-biblioref">Brück and Esenaliev 2018</a>; <a href="#ref-wb_uzb_2018" role="doc-biblioref">World Bank 2018</a>)</span>.</p>
</section>
</section>
<section id="data-and-measurement" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="data-and-measurement"><span class="header-section-number">3</span> Data and Measurement</h2>
<section id="core-data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="core-data"><span class="header-section-number">3.1</span> Core Data</h3>
<p>The main source is the Life in Transition Survey (LiTS) for 2010, 2016, and 2022-23. These repeated cross-sections provide comparable information on respondents’ own education, parental education, age, sex, and place of residence. Regional labels are harmonized with a locked cross-wave mapping before pooled estimation; regional coverage still differs by wave, so regional results are interpreted as composition-conditional rather than fully balanced panel comparisons.</p>
<p>The analytical sample is restricted to respondents aged 25-64 so that own education is largely complete. Cohorts are grouped as 25-34, 35-44, 45-54, and 55-64. Weighted estimates are used throughout, and subgroup outputs are suppressed when the valid cell size is below 30.</p>
<p>The Household Budget Survey is used only as a supplementary source for context and construct validation, especially around household structure, migration, schooling expenses, tutoring, and internet access. Because direct parent-child linkage in HBS is only partially supported in the current audit, it is not the source of the intergenerational estimates reported here.</p>
</section>
<section id="education-measures" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="education-measures"><span class="header-section-number">3.2</span> Education Measures</h3>
<p>The paper uses two measurement families built from a single parental-education harmonization rule. LiTS parental-schooling responses vary somewhat across waves in wording and granularity, so all observed mother and father responses are first mapped onto a common six-category ladder: no formal education, primary, lower secondary, upper secondary, post-secondary non-tertiary, and tertiary. When both parents are observed, the analysis uses the higher reported category as the parental education measure; when only one parent’s schooling is available, the observed value is retained. This rule keeps the comparison consistent across waves while limiting attrition from asymmetric parental reporting. Appendix D2 shows that the rank-based national series is qualitatively stable under alternative parent constructions, although some category-based rates are more sensitive to whether the parent proxy uses the maximum, an average, or a single observed parent.</p>
<p>That harmonized ladder then supports two complementary measures. First, the paper constructs an ordered education score used for category-based mobility rates and pooled attainment regressions. Second, it converts both respondent and parental schooling into within-wave weighted percentile ranks for the rank-rank persistence models. The category-based outcomes preserve the intuitive language of upward mobility, downward mobility, and same-category persistence. The rank-based outcomes, by contrast, are better suited to cross-wave comparison because they are less sensitive to modest questionnaire differences and to aggregate educational expansion. Reporting both is therefore deliberate rather than redundant: one family preserves substantive interpretability, while the other provides the paper’s preferred cross-wave benchmark.</p>
</section>
<section id="mobility-outcomes" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="mobility-outcomes"><span class="header-section-number">3.3</span> Mobility Outcomes</h3>
<p>The main outcomes are:</p>
<ul>
<li>Rank-rank slope: the relationship between own education rank and parental education rank within each wave.</li>
<li>Upward mobility: an indicator that own education exceeds parental education.</li>
<li>Downward mobility: an indicator that own education is lower than parental education.</li>
<li>Persistence: an indicator that own education remains at the same category as parental education.</li>
</ul>
<p>These measures are reported nationally and, where the denominator permits, by subgroup.</p>
</section>
<section id="covariates" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="covariates"><span class="header-section-number">3.4</span> Covariates</h3>
<p>The core covariates in the pooled correlates models are urban residence, female, migration exposure, and multigenerational household structure, with region, cohort, and wave fixed effects. These were selected through the project’s audit and coverage rules and represent the active set of non-core controls in the current design.</p>
</section>
<section id="pandemic-mechanism-variables" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="pandemic-mechanism-variables"><span class="header-section-number">3.5</span> Pandemic Mechanism Variables</h3>
<p>The 2022-23 LiTS child module is used to create descriptive indicators for remote-learning disruption, learning support, and home-learning constraints. These include switching to online learning, switching to hybrid learning, education stopping during COVID, school closure without online learning, shared-device use, support from mother, father, or relatives, and indicators for internet, device, cost, and time-balance challenges.</p>
<p>The mechanism sample is much smaller than the full LiTS IV sample. The child-module flow moves from 1006 Uzbekistan respondents in LiTS IV to 650 with child-module eligibility information, 186 with a child enrolled before COVID, and 183 with non-missing parental schooling. This extension is therefore used to illustrate patterns rather than to support broad generalization.</p>
</section>
</section>
<section id="empirical-strategy" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="empirical-strategy"><span class="header-section-number">4</span> Empirical Strategy</h2>
<p>The empirical strategy has three modules and uses one compact notation throughout. Let <span class="math inline">\(Y_{iw}\)</span> denote respondent <span class="math inline">\(i\)</span>’s educational outcome in wave <span class="math inline">\(w\)</span>, and let <span class="math inline">\(P_{iw}\)</span> denote parental education measured on the corresponding scale. In Module A, <span class="math inline">\(Y_{iw}\)</span> and <span class="math inline">\(P_{iw}\)</span> are within-wave education ranks. In Module B, <span class="math inline">\(Y_i\)</span> alternates across respondent rank, the harmonized education score, an indicator for upward mobility, and an indicator for same-category persistence; <span class="math inline">\(P_i\)</span> likewise denotes parental rank, the parental education score, or a set of parental education-category indicators. <span class="math inline">\(U_i\)</span> and <span class="math inline">\(F_i\)</span> indicate urban residence and female, <span class="math inline">\(X_i\)</span> collects migration exposure and multigenerational household structure, <span class="math inline">\(D_{ti}\)</span> is a wave indicator for <span class="math inline">\(t \in \{2016, 2022\}\)</span> with 2010 as the omitted category, and <span class="math inline">\(\mu_r\)</span>, <span class="math inline">\(\lambda_c\)</span>, and <span class="math inline">\(\tau_w\)</span> denote region, cohort, and wave effects. In Module C, <span class="math inline">\(L_i\)</span> indicates low parental education and <span class="math inline">\(M_i\)</span> a male child.</p>
<section id="module-a-mobility-levels-and-trends" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="module-a-mobility-levels-and-trends"><span class="header-section-number">4.1</span> Module A: Mobility Levels and Trends</h3>
<p>The first module estimates national mobility levels by wave. Its core descriptive specification is:</p>
<p><span class="math display">\[
Y_{iw} = \alpha_w + \beta_w P_{iw} + \varepsilon_{iw}
\]</span></p>
<p>where <span class="math inline">\(Y_{iw}\)</span> and <span class="math inline">\(P_{iw}\)</span> are respondent and parental education ranks within wave <span class="math inline">\(w\)</span>. The coefficient <span class="math inline">\(\beta_w\)</span> is the within-wave persistence slope: larger values imply that respondent rank tracks parental rank more closely and therefore signal lower relative mobility. The same module also reports weighted rates of upward mobility, downward mobility, and same-category persistence on the harmonized categorical scale.</p>
</section>
<section id="module-b-correlates-of-mobility" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="module-b-correlates-of-mobility"><span class="header-section-number">4.2</span> Module B: Correlates of Mobility</h3>
<p>The second module estimates pooled correlates models with region, cohort, and wave fixed effects. Its pooled benchmark is:</p>
<p><span class="math display">\[
Y_i
= \alpha + \beta P_i
+ \sum_{t \in \{2016, 2022\}} \theta_t \left(P_i \times D_{ti}\right)
+ \rho_1 U_i + \rho_2 F_i + X_i' \gamma + \mu_r + \lambda_c + \tau_w + \varepsilon_i
\]</span></p>
<p>In the persistence-trend specification, <span class="math inline">\(Y_i\)</span> is respondent rank and <span class="math inline">\(P_i\)</span> is parental rank, so <span class="math inline">\(\theta_t\)</span> captures whether the parent-child gradient in wave <span class="math inline">\(t\)</span> differs from 2010 after conditioning on controls and fixed effects. In the attainment model, <span class="math inline">\(Y_i\)</span> becomes the harmonized education score and <span class="math inline">\(\beta\)</span> is the conditional association between parental and respondent schooling. In the upward-mobility model, <span class="math inline">\(P_i\)</span> is replaced by parental education-category indicators, so the coefficients compare transition probabilities relative to the upper-secondary reference group. The persistence heterogeneity model keeps the same pooled structure but augments it with <span class="math inline">\(P_i \times U_i\)</span>, <span class="math inline">\(P_i \times F_i\)</span>, and <span class="math inline">\(P_i \times D_{2022,i}\)</span>. Throughout, the coefficients are interpreted as conditional associations rather than causal effects.</p>
</section>
<section id="module-c-pandemic-era-mechanisms" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="module-c-pandemic-era-mechanisms"><span class="header-section-number">4.3</span> Module C: Pandemic-Era Mechanisms</h3>
<p>The third module uses the 2022-23 child module to examine whether disruption and support patterns differ by parental education. Its descriptive heterogeneity specification is:</p>
<p><span class="math display">\[
Y_i = \alpha + \beta L_i + \delta_1 U_i + \delta_2 M_i + \kappa \left(L_i \times U_i\right) + \mu_r + \varepsilon_i
\]</span></p>
<p>where <span class="math inline">\(Y_i\)</span> is a binary child-module outcome estimated with a weighted logit model and region fixed effects. In the main text, the focal case is education stoppage during COVID, so <span class="math inline">\(\beta\)</span> is a log-odds coefficient comparing lower- and higher-parent-education households conditional on controls, while <span class="math inline">\(\kappa\)</span> indicates whether that log-odds gap differs between urban and non-urban households. Parallel estimates for online switching, school closure without online learning, and the broad remote-learning-challenge indicator are reported in the appendix. These regressions are descriptive heterogeneity exercises rather than identification strategies.</p>
</section>
</section>
<section id="descriptive-results" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="descriptive-results"><span class="header-section-number">5</span> Descriptive Results</h2>
<section id="sample-composition-and-completeness" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="sample-composition-and-completeness"><span class="header-section-number">5.1</span> Sample Composition and Completeness</h3>
<p>Before turning to the mobility estimates, Table <a href="#tbl-sample-composition" class="quarto-xref">Table&nbsp;1</a> establishes the analytical base by wave. The age-restricted Uzbekistan LiTS samples contain 1,157 respondents in 2010, 1,240 in 2016, and 794 in 2022-23. The 2022-23 wave is somewhat more female in the unweighted analytical sample, although the weighted estimation sample is much closer to balanced, while the cohort mix remains centered on the younger and middle adult cohorts in all three surveys.</p>
<p>The more consequential descriptive issue is now uncertainty rather than missingness. After harmonization, respondents’ own education is fully observed in all three waves, while parental education remains observed for 81.1 percent of the 2010 sample, 95.6 percent of the 2016 sample, and 98.1 percent of the 2022-23 sample. The latest-wave caution therefore comes less from a collapsing denominator than from wider confidence intervals in subgroup and regional descriptives.</p>
<div class="cell">
<div id="tbl-sample-composition" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sample-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Analytical sample composition and completeness by LiTS wave.
</figcaption>
<div aria-describedby="tbl-sample-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 33%">
<col style="width: 16%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">Valid N</th>
<th style="text-align: left;">Female share</th>
<th style="text-align: left;">Urban share</th>
<th style="text-align: left;">Cohort shares (25-34 / 35-44 / 45-54 / 55-64)</th>
<th style="text-align: left;">Own education missing</th>
<th style="text-align: left;">Parental education missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2010</td>
<td style="text-align: left;">1,157</td>
<td style="text-align: left;">61.6 percent</td>
<td style="text-align: left;">33.4 percent</td>
<td style="text-align: left;">33.8 / 30.3 / 22.9 / 13.1</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">18.9 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">1,240</td>
<td style="text-align: left;">54.7 percent</td>
<td style="text-align: left;">41.7 percent</td>
<td style="text-align: left;">25.6 / 26.6 / 24.5 / 23.3</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">4.4 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022-23</td>
<td style="text-align: left;">794</td>
<td style="text-align: left;">66.9 percent</td>
<td style="text-align: left;">36.5 percent</td>
<td style="text-align: left;">32.7 / 29.2 / 23.4 / 14.6</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">1.9 percent</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Table <a href="#tbl-sample-composition" class="quarto-xref">Table&nbsp;1</a> combines the published Tier A sample and completeness outputs with simple analytical-sample composition shares from the harmonized LiTS file; the main takeaway is that the descriptive section rests on usable national samples in every wave and that the harmonized adult sample retains broad parental-education coverage even in 2022-23.</p>
</section>
<section id="national-mobility-metrics-by-wave" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="national-mobility-metrics-by-wave"><span class="header-section-number">5.2</span> National Mobility Metrics by Wave</h3>
<p>Table <a href="#tbl-mobility-metrics" class="quarto-xref">Table&nbsp;2</a> reports the paper’s locked national mobility measures in a by-wave layout. The rank-rank slope rises from <strong>0.133</strong> in 2010 to <strong>0.307</strong> in 2016 and remains at <strong>0.253</strong> in 2022-23; the corresponding 95 percent confidence intervals are [0.075, 0.190], [0.254, 0.359], and [0.195, 0.310]. Category-based rates tell a similar broad story, with persistence rising and downward mobility falling in the later waves.</p>
<p>The harmonized denominator is now aligned across the rank and category measures within each wave. In 2022-23, both the rank-rank slope and the category-based rates rely on 779 valid observations. The main caution is therefore inferential rather than mechanical: the 2022 national estimates remain noisier than the 2016 values, and several subgroup or regional intervals are wide.</p>
<div class="cell">
<div id="tbl-mobility-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mobility-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: National mobility metrics by LiTS wave.
</figcaption>
<div aria-describedby="tbl-mobility-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 28%">
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">Rank-rank slope (95% CI)</th>
<th style="text-align: left;">Upward mobility</th>
<th style="text-align: left;">Downward mobility</th>
<th style="text-align: left;">Persistence</th>
<th style="text-align: left;">Valid N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2010</td>
<td style="text-align: left;">0.133 [0.075, 0.190]</td>
<td style="text-align: left;">30.5 percent</td>
<td style="text-align: left;">25.4 percent</td>
<td style="text-align: left;">44.1 percent</td>
<td style="text-align: left;">936</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">0.307 [0.254, 0.359]</td>
<td style="text-align: left;">25.6 percent</td>
<td style="text-align: left;">18.1 percent</td>
<td style="text-align: left;">56.3 percent</td>
<td style="text-align: left;">1,186</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022-23</td>
<td style="text-align: left;">0.253 [0.195, 0.310]</td>
<td style="text-align: left;">24.6 percent</td>
<td style="text-align: left;">8.1 percent</td>
<td style="text-align: left;">67.3 percent</td>
<td style="text-align: left;">779</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Table <a href="#tbl-mobility-metrics" class="quarto-xref">Table&nbsp;2</a> and Figures <a href="#fig-rank-rank" class="quarto-xref">Figure&nbsp;1</a> and <a href="#fig-directional-rates" class="quarto-xref">Figure&nbsp;2</a> tell the same high-level story: educational persistence is substantial in every wave, the steepest descriptive increase occurs between 2010 and 2016, and the 2022-23 profile remains more persistent than the 2010 baseline without clearly exceeding the 2016 peak once uncertainty is shown.</p>
<div id="fig-rank-rank" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Rank-rank slope by LiTS wave.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/tier_a_rank_rank_by_wave.png" class="img-fluid figure-img" alt="Rank-rank slope by LiTS wave.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Rank-rank slope by LiTS wave.
</figcaption>
</figure>
</div>
<div id="fig-directional-rates" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Directional mobility rates by LiTS wave.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-directional-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/tier_a_directional_rates_by_wave.png" class="img-fluid figure-img" alt="Directional mobility rates by LiTS wave.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-directional-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Directional mobility rates by LiTS wave.
</figcaption>
</figure>
</div>
</section>
<section id="transition-structure" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="transition-structure"><span class="header-section-number">5.3</span> Transition Structure</h3>
<p>The by-wave rates are easier to interpret alongside the transition structure in Table <a href="#tbl-transition-structure" class="quarto-xref">Table&nbsp;3</a>. In both 2010 and 2016, respondents from lower-secondary and primary parental origins most often reach upper secondary, while respondents from upper-secondary parental origins remain concentrated in the same category. This is consistent with a system that permits some upward movement from lower origins but still exhibits strong persistence around the upper-secondary category that dominates the analytical sample.</p>
<p>The 2022-23 transition matrix remains thin at the lowest parental origins, but it is no longer confined to a single usable row. The tertiary parental-origin row shows 87.3 percent same-category persistence out of 503 valid cases, while the upper-secondary parental-origin row shows 63.0 percent movement into tertiary and 36.4 percent same-category persistence out of 263 valid cases. The main takeaway is that the transition evidence reinforces strong persistence at the top of the ladder while lower-origin 2022 rows remain too sparse for fine-grained inference.</p>
<div class="cell">
<div id="tbl-transition-structure" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-transition-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Transition structure for parental-origin categories with usable cell counts.
</figcaption>
<div aria-describedby="tbl-transition-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">Parental origin</th>
<th style="text-align: left;">Own: Primary</th>
<th style="text-align: left;">Own: Lower secondary</th>
<th style="text-align: left;">Own: Upper secondary</th>
<th style="text-align: left;">Parent-origin N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2010</td>
<td style="text-align: left;">Primary</td>
<td style="text-align: left;">2.7 percent</td>
<td style="text-align: left;">20.1 percent</td>
<td style="text-align: left;">65.6 percent</td>
<td style="text-align: left;">48</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">2010</td>
<td style="text-align: left;">Lower secondary</td>
<td style="text-align: left;">0.6 percent</td>
<td style="text-align: left;">25.5 percent</td>
<td style="text-align: left;">60.9 percent</td>
<td style="text-align: left;">232</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">2010</td>
<td style="text-align: left;">Upper secondary</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">18.0 percent</td>
<td style="text-align: left;">69.7 percent</td>
<td style="text-align: left;">433</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">2016</td>
<td style="text-align: left;">Primary</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">14.2 percent</td>
<td style="text-align: left;">56.1 percent</td>
<td style="text-align: left;">39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2016</td>
<td style="text-align: left;">Lower secondary</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">17.1 percent</td>
<td style="text-align: left;">49.6 percent</td>
<td style="text-align: left;">187</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">2016</td>
<td style="text-align: left;">Upper secondary</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">6.0 percent</td>
<td style="text-align: left;">64.3 percent</td>
<td style="text-align: left;">429</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="descriptive-heterogeneity" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="descriptive-heterogeneity"><span class="header-section-number">5.4</span> Descriptive Heterogeneity</h3>
<section id="cohort-profiles" class="level4" data-number="5.4.1">
<h4 data-number="5.4.1" class="anchored" data-anchor-id="cohort-profiles"><span class="header-section-number">5.4.1</span> Cohort Profiles</h4>
<p>Figure <a href="#fig-cohort-rank-rank" class="quarto-xref">Figure&nbsp;3</a> shows that the rank-based persistence gradient differs across cohorts, even though all cohort profiles remain positive. The youngest adult cohort moves from a slope of <strong>0.181</strong> in 2010 to <strong>0.196</strong> in 2022-23, while the oldest cohort stays closer to one quarter throughout the period. These are descriptive cross-cohort differences rather than cohort effects identified from a panel.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cohort-rank-rank" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cohort-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="00_main_files/figure-html/fig-cohort-rank-rank-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cohort-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Rank-rank persistence by cohort and LiTS wave.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The main takeaway is that cohort profiles are heterogeneous in levels, but they do not overturn the broader descriptive picture of substantial persistence across all waves.</p>
</section>
<section id="regional-variation" class="level4" data-number="5.4.2">
<h4 data-number="5.4.2" class="anchored" data-anchor-id="regional-variation"><span class="header-section-number">5.4.2</span> Regional Variation</h4>
<p>Regional dispersion is most legible in the rank-based measure, because the 2022 category-based regional outputs remain sparse for many origin cells. Figure <a href="#fig-region-rank-rank" class="quarto-xref">Figure&nbsp;4</a> ranks the 2022-23 regional slopes and shows a wide descriptive spread around the national slope of <strong>0.253</strong>. The highest observed persistence appears in Tashkent city at <strong>0.734</strong>, while Khorezm region sits near <strong>0.036</strong>. These regional differences are descriptive and several intervals remain wide, so they should be read as dispersion rather than ranked certainty.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region-rank-rank" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="00_main_files/figure-html/fig-region-rank-rank-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Regional dispersion in the 2022-23 rank-rank slope.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The main takeaway is that regional differences are descriptively large enough to matter for interpretation, even though the paper does not treat them as identified regional effects and several regional estimates remain imprecise.</p>
</section>
<section id="subgroup-split" class="level4" data-number="5.4.3">
<h4 data-number="5.4.3" class="anchored" data-anchor-id="subgroup-split"><span class="header-section-number">5.4.3</span> Subgroup Split</h4>
<p>Figure <a href="#fig-upward-urban-rural" class="quarto-xref">Figure&nbsp;5</a> brings one existing subgroup visual into the main text. The urban-rural split is worth showing because it connects directly to the paper’s pooled correlates framework, but it should still be read as descriptive because the figure is based on the category-coded upward-mobility rate rather than the paper’s preferred rank-based trend benchmark.</p>
<p>The companion gender split is not promoted to the main text because the 2022-23 male category-mobility sample is only 260 with a weighted effective N of about 164.9, which makes that panel less informative than the urban-rural comparison.</p>
<div id="fig-upward-urban-rural" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Upward mobility by urban and rural residence.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-upward-urban-rural-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/tier_a_upward_by_urban_rural.png" class="img-fluid figure-img" alt="Upward mobility by urban and rural residence.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-upward-urban-rural-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Upward mobility by urban and rural residence.
</figcaption>
</figure>
</div>
<p>The main takeaway is that subgroup descriptives are useful for orientation, but the rank-based national series remains the most reliable summary of cross-wave mobility levels.</p>
</section>
</section>
</section>
<section id="correlates-of-educational-mobility" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="correlates-of-educational-mobility"><span class="header-section-number">6</span> Correlates of Educational Mobility</h2>
<section id="pooled-persistence-trend-model" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="pooled-persistence-trend-model"><span class="header-section-number">6.1</span> Pooled Persistence-Trend Model</h3>
<p>The pooled rank-based persistence model shows a clear positive association between parental rank and respondent rank. The coefficient on parental rank is <strong>0.154</strong>, the interaction with 2016 is positive and precisely estimated at <strong>0.160</strong>, and the additional 2022 interaction is also positive but only marginally estimated at <strong>0.094</strong>.</p>
<p>This result sharpens the descriptive reading. Once the model adds region, cohort, wave fixed effects, and the selected covariates, the data support a stronger parent-child gradient in 2016 than in 2010, while the 2022-23 gradient remains above the 2010 baseline but is less clearly distinguished from the 2016 level. The pooled evidence therefore supports persistence and a mid-period strengthening more clearly than a monotonic worsening in every later wave.</p>
</section>
<section id="attainment-score-model" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="attainment-score-model"><span class="header-section-number">6.2</span> Attainment-Score Model</h3>
<p>The attainment-score regression shows a robust positive association between parental education and own educational attainment. The coefficient on parental education score is <strong>0.245</strong> and is precisely estimated. This is the clearest correlates result in the paper: better-educated parents are associated with higher educational attainment among adult children even after adding fixed effects and the active covariates.</p>
<p>Among the non-parental covariates, none is precisely estimated in the current pooled specification. The female coefficient is slightly negative at <strong>-0.036</strong>, while urban residence, migration exposure, and multigenerational household structure are likewise imprecisely estimated. The central correlates result is therefore narrow: parental educational background remains the strongest and most stable predictor in the pooled attainment model.</p>
</section>
<section id="upward-mobility-models" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="upward-mobility-models"><span class="header-section-number">6.3</span> Upward Mobility Models</h3>
<p>The upward-mobility linear probability models are useful mainly for showing where upward transitions are mechanically more likely. Relative to the upper-secondary reference group, respondents from primary-educated households and lower-secondary households have much higher estimated probabilities of upward mobility, with coefficients of <strong>0.679</strong> and <strong>0.496</strong>, respectively.</p>
<p>The non-parental covariates in the upward-mobility models are weaker. Urban residence is close to zero, migration exposure is not precisely estimated, and multigenerational household structure is negligible. The one clearer non-parental pattern is a lower upward-mobility probability for women conditional on the same controls. In substantive terms, the upward-mobility models still mostly reflect where households begin in the parental education ladder rather than strong independent roles for the additional covariates.</p>
</section>
<section id="heterogeneity-in-persistence" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="heterogeneity-in-persistence"><span class="header-section-number">6.4</span> Heterogeneity in Persistence</h3>
<p>The persistence heterogeneity model shows a positive association between parental education score and the probability of remaining in the same education category as one’s parents. The coefficient on parental education score is <strong>0.083</strong> and is precisely estimated.</p>
<p>The interaction pattern differs from the earlier draft. The urban interaction is close to zero and not precisely estimated, while the female interaction is negative at <strong>-0.028</strong> with p-value <strong>0.050</strong>. The interaction between parent education and the 2022 wave is positive at <strong>0.161</strong> and precisely estimated. A cautious reading is that parental education translates into same-category persistence across the pooled sample, with a stronger gradient in 2022-23 and weaker transmission among women in this specification. Table <a href="#tbl-pooled-correlates" class="quarto-xref">Table&nbsp;4</a> collects the selected coefficients discussed in Section 6.</p>
<div class="cell">
<div id="tbl-pooled-correlates" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pooled-correlates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Selected pooled correlates estimates.
</figcaption>
<div aria-describedby="tbl-pooled-correlates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 28%">
<col style="width: 37%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Estimate</th>
<th style="text-align: left;">Std. Error</th>
<th style="text-align: left;">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Parent rank</td>
<td style="text-align: left;">0.154</td>
<td style="text-align: left;">0.041</td>
<td style="text-align: left;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Parent rank x 2016</td>
<td style="text-align: left;">0.160</td>
<td style="text-align: left;">0.047</td>
<td style="text-align: left;">0.005</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Parent rank x 2022-23</td>
<td style="text-align: left;">0.094</td>
<td style="text-align: left;">0.067</td>
<td style="text-align: left;">0.182</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Attainment score</td>
<td style="text-align: left;">Parent education score</td>
<td style="text-align: left;">0.245</td>
<td style="text-align: left;">0.022</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">Attainment score</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">-0.036</td>
<td style="text-align: left;">0.034</td>
<td style="text-align: left;">0.314</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">Upward mobility</td>
<td style="text-align: left;">Parent education: primary</td>
<td style="text-align: left;">0.679</td>
<td style="text-align: left;">0.036</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">Upward mobility</td>
<td style="text-align: left;">Parent education: lower secondary</td>
<td style="text-align: left;">0.496</td>
<td style="text-align: left;">0.045</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">29</td>
<td style="text-align: left;">Persistence heterogeneity</td>
<td style="text-align: left;">Parent education score</td>
<td style="text-align: left;">0.083</td>
<td style="text-align: left;">0.013</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">36</td>
<td style="text-align: left;">Persistence heterogeneity</td>
<td style="text-align: left;">Parent education score x 2022-23</td>
<td style="text-align: left;">0.161</td>
<td style="text-align: left;">0.040</td>
<td style="text-align: left;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">34</td>
<td style="text-align: left;">Persistence heterogeneity</td>
<td style="text-align: left;">Parent education score x urban</td>
<td style="text-align: left;">0.023</td>
<td style="text-align: left;">0.020</td>
<td style="text-align: left;">0.280</td>
</tr>
<tr class="odd">
<td style="text-align: left;">35</td>
<td style="text-align: left;">Persistence heterogeneity</td>
<td style="text-align: left;">Parent education score x female</td>
<td style="text-align: left;">-0.028</td>
<td style="text-align: left;">0.013</td>
<td style="text-align: left;">0.050</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="household-support-environment-from-hbs" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="household-support-environment-from-hbs"><span class="header-section-number">6.5</span> Household Support Environment from HBS</h3>
<p>Supplementary HBS evidence is used here only to characterize the household support environment around schooling, not to replace the core LiTS intergenerational estimates. Across pooled HBS 2021-2025 households, 65.7 percent had an enrolled member, 62.6 percent reported positive education spending, 14.2 percent reported tutoring, 16.3 percent had an emigrant member, and 14.8 percent received remittances; internet access is observed for 79.7 percent of households in the 2021-2024 internet module. These patterns provide context for interpretation by showing that schooling support, migration-linked resources, and connectivity constraints sit inside the same household environment as the LiTS persistence patterns.</p>
<p>The HBS linkage diagnostics in Appendix H also show why HBS remains supplementary. Under a conservative co-resident linkage rule, only 9.3 percent of HBS adults ages 25-64 are linkable, and that linked sample is materially younger and much less female than the full adult sample. HBS therefore informs the household support environment, but it is not a direct substitute for the headline LiTS intergenerational estimates.</p>
<div class="cell">
<div id="tbl-hbs-context" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hbs-context-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Supplementary HBS household support environment, pooled 2021-2025.
</figcaption>
<div aria-describedby="tbl-hbs-context-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 58%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Household support indicator</th>
<th style="text-align: left;">National</th>
<th style="text-align: left;">Urban</th>
<th style="text-align: left;">Rural</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Households with enrolled members</td>
<td style="text-align: left;">65.7 percent</td>
<td style="text-align: left;">63.5 percent</td>
<td style="text-align: left;">67.9 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">Households with positive education spending</td>
<td style="text-align: left;">62.6 percent</td>
<td style="text-align: left;">60.3 percent</td>
<td style="text-align: left;">64.9 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households with tutoring</td>
<td style="text-align: left;">14.2 percent</td>
<td style="text-align: left;">14.2 percent</td>
<td style="text-align: left;">14.1 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">Households with emigrant member</td>
<td style="text-align: left;">16.3 percent</td>
<td style="text-align: left;">13.2 percent</td>
<td style="text-align: left;">19.4 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households receiving remittances</td>
<td style="text-align: left;">14.8 percent</td>
<td style="text-align: left;">11.9 percent</td>
<td style="text-align: left;">17.8 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remittance households using remittances for education</td>
<td style="text-align: left;">19.6 percent</td>
<td style="text-align: left;">20.3 percent</td>
<td style="text-align: left;">19.1 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households with internet access</td>
<td style="text-align: left;">79.7 percent</td>
<td style="text-align: left;">79.6 percent</td>
<td style="text-align: left;">79.8 percent</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="bounded-lits-iv-child-module-extension" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="bounded-lits-iv-child-module-extension"><span class="header-section-number">7</span> Bounded LiTS IV Child Module Extension</h2>
<section id="sample-and-disruption-profile" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="sample-and-disruption-profile"><span class="header-section-number">7.1</span> Sample and Disruption Profile</h3>
<p>The child-module extension is deliberately kept secondary to Modules A and B. It is based on 183 respondents with a child enrolled before COVID and non-missing parental schooling. Table <a href="#tbl-modulec-sample" class="quarto-xref">Table&nbsp;6</a> reports the sample flow.</p>
<p>Within this restricted sample, disruption and household substitution were substantial: <strong>78.3 percent</strong> report education stoppage during COVID, <strong>75.8 percent</strong> report at least one remote-learning challenge, and mothers are reported as the learning-support channel in <strong>87.0 percent</strong> of cases. Additional descriptive splits and the fragility checks for the mechanism regressions are reported in the technical appendix so that the main text remains focused on the strongest facts.</p>
<div class="cell">
<div id="tbl-modulec-sample" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-modulec-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: LiTS IV child-module sample construction for Uzbekistan.
</figcaption>
<div aria-describedby="tbl-modulec-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 90%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Uzbekistan LiTS IV respondents</td>
<td style="text-align: right;">1006.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Respondents with child module eligibility info (q713 non-missing)</td>
<td style="text-align: right;">650.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Respondents with child enrolled pre-COVID (q713 = yes)</td>
<td style="text-align: right;">186.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mechanism sample with non-missing parental schooling</td>
<td style="text-align: right;">183.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Parental schooling median threshold (years)</td>
<td style="text-align: right;">13.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baseline low-parent-education group size</td>
<td style="text-align: right;">114.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baseline higher-parent-education group size</td>
<td style="text-align: right;">69.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="main-regression-takeaway" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="main-regression-takeaway"><span class="header-section-number">7.2</span> Main Regression Takeaway</h3>
<p>The adjusted regression evidence is much weaker than the descriptive disruption rates. In the baseline weighted median-split specification, the coefficient on low parental education in the stoppage model is <strong>0.025</strong> with p-value <strong>0.952</strong>, and the descriptive stoppage rates are nearly identical: <strong>78.2 percent</strong> among children from lower-parent-education households versus <strong>78.0 percent</strong> among those from higher-parent-education households.</p>
<p>The technical appendix shows that the stoppage coefficient is fragile across weighting and threshold choices. Under the strict <code>&lt;=9</code> split, the low-parent-education group falls to <strong>7</strong> observations (vs <strong>176</strong> in the comparison group), so this scenario is treated as degenerate support (degenerate_low_group_support) rather than an interpretable robustness estimate. Module C therefore contributes bounded descriptive evidence on household vulnerability and learning support, not a stable adjusted parental-education gradient and not causal evidence on pandemic mechanisms.</p>
</section>
</section>
<section id="discussion-and-policy-implications" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="discussion-and-policy-implications"><span class="header-section-number">8</span> Discussion and Policy Implications</h2>
<p>Three broad conclusions emerge from the analysis.</p>
<p>First, Uzbekistan exhibits substantial intergenerational educational persistence. Descriptive persistence rises strongly from 2010 to 2016 and remains above the 2010 level in 2022-23. The pooled rank-based model supports a stronger persistence gradient in 2016 relative to 2010, while the additional 2022 increment is less precisely estimated.</p>
<p>Second, parental education is the most consistent predictor in the pooled correlates models. The data provide less clear evidence that migration exposure or multigenerational household structure independently explain mobility once the core controls and fixed effects are added, although these factors may still matter through channels the present specifications do not capture well.</p>
<p>Third, the pandemic mechanism evidence underscores the practical importance of household learning conditions. Device sharing, internet quality, and time- or cost-related constraints were common, and support was overwhelmingly provided by mothers. What the child module establishes most clearly is the scale of disruption and household substitution, not a robust adjusted stoppage gap by parental education.</p>
<p>These findings imply several policy priorities. The first is to reduce the degree to which educational attainment depends on parental background through earlier remedial support, stronger transitions across schooling stages, and wider access to quality secondary and post-secondary pathways. The second is to address spatial and household bottlenecks directly. Even without a precise pooled urban coefficient, the broader descriptive evidence points to local infrastructure, service access, and household support conditions as meaningful constraints on mobility.</p>
<p>The third priority is to strengthen household support capacity in periods of disruption. The child module shows that digital inclusion is not only a question of nominal internet access, but also of connection quality, device availability, and adults’ ability to help children learn. A related implication is that education policy should recognize mothers’ support burden as a real part of learning continuity rather than assume that home-based adjustment is costless inside the household.</p>
</section>
<section id="limitations" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="limitations"><span class="header-section-number">9</span> Limitations</h2>
<p>This paper has four main limitations.</p>
<p>First, the three LiTS waves are repeated cross-sections rather than a panel, so changes over time should be interpreted as changes in population-level patterns rather than changes within fixed families.</p>
<p>Second, the comparability of some parental education information across waves is imperfect, which is why the rank-based measures are more reliable than some category-based comparisons.</p>
<p>Third, several 2022-23 subgroup and regional estimates remain noisy even after the harmonized denominator problem is resolved. The national 2022 profile is informative, but some disaggregated category-based and regional comparisons still have wide confidence intervals or sparse origin cells.</p>
<p>Fourth, the pandemic mechanism module is based on a limited child subsample and is not a causal design. Its adjusted parental-education coefficients are also fragile across weighting and threshold choices, so it is useful for describing disruption and support patterns rather than for establishing a stable mechanism.</p>
<p>These limitations do not undermine the central contribution of the paper, but they do shape the appropriate scope of the conclusions.</p>
</section>
<section id="conclusion" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">10</span> Conclusion</h2>
<p>This paper provides structured multi-wave evidence on intergenerational educational mobility in Uzbekistan using LiTS 2010, 2016, and 2022-23. The results indicate substantial educational persistence across generations. Descriptive persistence rises from 2010 to 2016 and remains elevated in 2022-23, while the pooled correlates models point to a stronger mid-period persistence gradient and continue to show parental education as the clearest predictor of children’s educational attainment.</p>
<p>The extension based on the LiTS IV child module shows that pandemic-era learning disruption was widespread and that household support, especially maternal support, was central to learning continuity. The same extension does not provide robust adjusted evidence that lower parental education raised the probability that education stopped during COVID.</p>
<p>The broader message is that improving educational mobility in Uzbekistan will require more than expanding formal access. It will require reducing the degree to which family background governs educational trajectories, especially through the unequal household conditions under which children study, recover from shocks, and convert schooling opportunities into completed attainment.</p>
</section>
<section id="bibliography" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-akarcay_polat_2017" class="csl-entry" role="listitem">
Akarçay-Gürbüz, Asli, and Seher Polat. 2017. <span>“Schooling Opportunities and Intergenerational Educational Mobility in <span>T</span>urkey.”</span> Working Paper. Piri Reis University; Yildiz Technical University.
</div>
<div id="ref-alam_tiwari_2020" class="csl-entry" role="listitem">
Alam, Andaleeb, and Priyanka Tiwari. 2020. <span>“Putting the <span>‘Learning’</span> Back in Remote Learning.”</span> UNICEF Office of Global Insight; Policy. <a href="https://www.unicef.org/globalinsight/media/1086/file/UNICEF-Global-Insight-remote-learning-issue-brief-2020.pdf">https://www.unicef.org/globalinsight/media/1086/file/UNICEF-Global-Insight-remote-learning-issue-brief-2020.pdf</a>.
</div>
<div id="ref-aydemir_yazici_2019" class="csl-entry" role="listitem">
Aydemir, Abdurrahman B., and Huseyin Yazici. 2019. <span>“Intergenerational Education Mobility and the Level of Development: Evidence from <span>T</span>urkey.”</span> <em>European Economic Review</em> 116: 160–85. <a href="https://doi.org/10.1016/j.euroecorev.2019.04.003">https://doi.org/10.1016/j.euroecorev.2019.04.003</a>.
</div>
<div id="ref-bruck_esenaliev_2018" class="csl-entry" role="listitem">
Brück, Tilman, and Damir Esenaliev. 2018. <span>“Post-Socialist Transition and Intergenerational Educational Mobility in <span>K</span>yrgyzstan.”</span> <em>Economics of Transition</em> 26 (1): 61–89. <a href="https://doi.org/10.1111/ecot.12136">https://doi.org/10.1111/ecot.12136</a>.
</div>
<div id="ref-causa_johansson_2010" class="csl-entry" role="listitem">
Causa, Orsetta, and Asa Johansson. 2010. <span>“Intergenerational Social Mobility in <span>OECD</span> Countries.”</span> Working Paper 707. OECD Economics Department. <a href="https://doi.org/10.1787/223106258208">https://doi.org/10.1787/223106258208</a>.
</div>
<div id="ref-chevalier_denny_mcmahon_2009" class="csl-entry" role="listitem">
Chevalier, Arnaud, Kevin Denny, and Dorren McMahon. 2009. <span>“A Multi-Country Study of Inter-Generational Educational Mobility.”</span> In <em>Education and Inequality Across Europe</em>, edited by Peter Dolton, Rita Asplund, and Erling Barth. Cheltenham: Edward Elgar.
</div>
<div id="ref-duong_2024" class="csl-entry" role="listitem">
Duong, Khanh. 2024. <span>“What Really Matters for Global Intergenerational Mobility?”</span> <em>PLOS ONE</em> 19 (6): e0302173. <a href="https://doi.org/10.1371/journal.pone.0302173">https://doi.org/10.1371/journal.pone.0302173</a>.
</div>
<div id="ref-guell_etal_2018" class="csl-entry" role="listitem">
Guell, Maia, Michele Pellizzari, Giovanni Pica, and Jose V. Rodriguez Mora. 2018. <span>“Correlating Social Mobility and Economic Outcomes.”</span> <em>The Economic Journal</em> 128 (612): F353–403. <a href="https://doi.org/10.1111/ecoj.12599">https://doi.org/10.1111/ecoj.12599</a>.
</div>
<div id="ref-hertz_2008" class="csl-entry" role="listitem">
Hertz, Tom, Tamara Jayasundera, Patrizio Piraino, Sibel Selcuk, Nicole Smith, and Alina Verashchagina. 2008. <span>“The Inheritance of Educational Inequality: International Comparisons and Fifty-Year Trends.”</span> <em>The B.E. Journal of Economic Analysis &amp; Policy</em> 7 (2). <a href="https://doi.org/10.2202/1935-1682.1775">https://doi.org/10.2202/1935-1682.1775</a>.
</div>
<div id="ref-iqbal_patrinos_2025" class="csl-entry" role="listitem">
Iqbal, Syedah Aroob, and Harry Anthony Patrinos. 2025. <span>“Learning During the Pandemic: Evidence from <span>U</span>zbekistan.”</span> <em>Prospects</em>. <a href="https://doi.org/10.1007/s11125-025-09736-w">https://doi.org/10.1007/s11125-025-09736-w</a>.
</div>
<div id="ref-munoz_najar_etal_2021" class="csl-entry" role="listitem">
Muñoz-Najar, Alberto, Alison Gilberto, Amer Hasan, Cristobal Cobo, João Pedro Azevedo, and Maryam Akmal. 2021. <span>“Remote Learning During <span>COVID</span>-19: Lessons from Today, Principles for Tomorrow.”</span> World Bank. <a href="https://documents.worldbank.org/en/publication/documents-reports/documentdetail/160271637074230077/remote-learning-during-covid-19-lessons-from-today-principles-for-tomorrow">https://documents.worldbank.org/en/publication/documents-reports/documentdetail/160271637074230077/remote-learning-during-covid-19-lessons-from-today-principles-for-tomorrow</a>.
</div>
<div id="ref-neidhoefer_etal_2024" class="csl-entry" role="listitem">
Neidhöfer, Guido, Matias Ciaschi, Leonardo Gasparini, and Jorge Serrano. 2024. <span>“Social Mobility and Economic Development.”</span> <em>Journal of Economic Growth</em> 29 (2): 327–59. <a href="https://doi.org/10.1007/s10887-023-09234-8">https://doi.org/10.1007/s10887-023-09234-8</a>.
</div>
<div id="ref-razzu_wambile_2022" class="csl-entry" role="listitem">
Razzu, Giovanni, and Ayago Wambile. 2022. <span>“Four Decades of Intergenerational Educational Mobility in Sub-<span>S</span>aharan <span>A</span>frica.”</span> <em>The Journal of Development Studies</em> 58 (5): 931–50. <a href="https://doi.org/10.1080/00220388.2021.2008366">https://doi.org/10.1080/00220388.2021.2008366</a>.
</div>
<div id="ref-stromberg_engzell_2025" class="csl-entry" role="listitem">
Strömberg, Ely, and Per Engzell. 2025. <span>“How Robust Are Country Rankings in Educational Mobility?”</span> <em>Sociological Science</em> 12: 891–922. <a href="https://doi.org/10.15195/v12.a36">https://doi.org/10.15195/v12.a36</a>.
</div>
<div id="ref-torche_2015" class="csl-entry" role="listitem">
Torche, Florencia. 2015. <span>“Intergenerational Mobility and Equality of Opportunity.”</span> <em>Archives Europ<span>é</span>ennes de Sociologie</em> 56 (3): 343–71. <a href="https://doi.org/10.1017/S0003975615000181">https://doi.org/10.1017/S0003975615000181</a>.
</div>
<div id="ref-unicef_compact_2024" class="csl-entry" role="listitem">
UNICEF. 2024. <span>“Partnership Compact for Education Reform.”</span> UNICEF Uzbekistan. <a href="https://www.unicef.org/uzbekistan/en/reports/partnership-compact-education-reform">https://www.unicef.org/uzbekistan/en/reports/partnership-compact-education-reform</a>.
</div>
<div id="ref-unicef_sitan_2020" class="csl-entry" role="listitem">
UNICEF Uzbekistan. 2020. <span>“Situation Analysis of Children in <span>U</span>zbekistan 2019/2020.”</span> UNICEF Uzbekistan. <a href="https://www.unicef.org/uzbekistan/en/press-releases/unicef-launches-situation-analysis-uzbekistan-children-and-warns-covid-19-pandemic">https://www.unicef.org/uzbekistan/en/press-releases/unicef-launches-situation-analysis-uzbekistan-children-and-warns-covid-19-pandemic</a>.
</div>
<div id="ref-unicef_sitan_2024" class="csl-entry" role="listitem">
———. 2024. <span>“Situation Analysis of Children and Adolescents in <span>U</span>zbekistan.”</span> UNICEF Uzbekistan. <a href="https://www.unicef.org/uzbekistan/en/reports/situation-analysis-children-and-adolescents-uzbekistan">https://www.unicef.org/uzbekistan/en/reports/situation-analysis-children-and-adolescents-uzbekistan</a>.
</div>
<div id="ref-urbina_2018" class="csl-entry" role="listitem">
Urbina, Daniela R. 2018. <span>“Intergenerational Educational Mobility During Expansion Reform: Evidence from <span>M</span>exico.”</span> <em>Population Research and Policy Review</em> 37 (3): 367–417. <a href="https://doi.org/10.1007/s11113-018-9466-4">https://doi.org/10.1007/s11113-018-9466-4</a>.
</div>
<div id="ref-verashchagina_2012" class="csl-entry" role="listitem">
Verashchagina, Alina. 2012. <span>“Education and Socioeconomic Mobility in Post-Communist Countries.”</span> In <em>Social Exclusion: Short and Long-Term Causes and Consequences</em>, edited by Giuliana Parodi and Dario Sciulli. AIEL Series in Labour Economics. Heidelberg: Springer.
</div>
<div id="ref-weide_etal_2024" class="csl-entry" role="listitem">
Weide, Roy van der, Christoph Lakner, Daniel Gerszon Mahler, Ambar Narayan, and Rakesh Gupta. 2024. <span>“Intergenerational Mobility Around the World: A New Database.”</span> <em>Journal of Development Economics</em> 166: 103167. <a href="https://doi.org/10.1016/j.jdeveco.2023.103167">https://doi.org/10.1016/j.jdeveco.2023.103167</a>.
</div>
<div id="ref-wb_modernizing_tertiary_2017" class="csl-entry" role="listitem">
World Bank. 2014. <span>“Uzbekistan: Modernizing Tertiary Education.”</span> World Bank. <a href="https://hdl.handle.net/10986/27992">https://hdl.handle.net/10986/27992</a>.
</div>
<div id="ref-wb_uzb_2018" class="csl-entry" role="listitem">
———. 2018. <span>“Uzbekistan Education Sector Analysis.”</span> AUS0000586. World Bank. <a href="https://documents.worldbank.org/en/publication/documents-reports/documentdetail/648681587857648494/uzbekistan-education-sector-analysis-final-report">https://documents.worldbank.org/en/publication/documents-reports/documentdetail/648681587857648494/uzbekistan-education-sector-analysis-final-report</a>.
</div>
<div id="ref-wb_gender_2024" class="csl-entry" role="listitem">
———. 2024. <span>“Country Gender Assessment: <span>U</span>zbekistan.”</span> World Bank. <a href="https://thedocs.worldbank.org/en/doc/752717e92c8ad1476bc6cb007bae8f1a-0080012024/original/uz-country-gender-assessment-2024-uz-pdf.pdf">https://thedocs.worldbank.org/en/doc/752717e92c8ad1476bc6cb007bae8f1a-0080012024/original/uz-country-gender-assessment-2024-uz-pdf.pdf</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>