project:
  type: default
  output-dir: outputs/publication

execute:
  echo: false
  warning: false
  message: false

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
  docx:
    toc: true

editor: visual
